# Copyright X-HEEP contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# ============================================================================
# Project Configuration
# ============================================================================
XALP := x-heep:x-alp:x-alp:0.0.1
mkfile_path := $(shell dirname "$(realpath $(firstword $(MAKEFILE_LIST)))")

$(info Executing from: $(mkfile_path))

# ============================================================================
# Python Environment Setup
# ============================================================================
VENVDIR ?= $(WORKDIR)/.venv
REQUIREMENTS_TXT ?= util/python-requirements.txt docs/python-requirements.txt
export FILE_FOR_HELP := $(mkfile_path)/Makefile

include Makefile.venv

# Select Python tooling (conda or venv)
ifdef CONDA_DEFAULT_ENV
  $(info Using Miniconda environment: $(CONDA_DEFAULT_ENV))
  FUSESOC := $(shell which fusesoc)
  PYTHON := $(shell which python)
else
  $(info Using virtual environment)
  FUSESOC := $(PWD)/$(VENV)/fusesoc
  PYTHON := $(PWD)/$(VENV)/python
endif

# ============================================================================
# Build Configuration
# ============================================================================
# FuseSoC arguments
FUSESOC_ARGS ?=

# Verilator simulation parameters
LOG_LEVEL ?= LOG_DEBUG
BINARY ?= $(mkfile_path)/sw/build/main.spm.elf
BOOTMODE ?= force
MAX_CYCLES ?= 1000000
# In JTAG mode, omit MAX_CYCLES so the sim runs until exit_valid (run_all=true)
ifeq ($(BOOTMODE),jtag)
MAX_CYCLES_ARG =
else
MAX_CYCLES_ARG = --MAX_CYCLES=$(MAX_CYCLES)
endif
BUILD_STAMP := build/.verilator-build-stamp

# Application build parameters
PROJECT ?= hello_world
TARGET ?= sim
LINKER ?= on_chip
LINK_FOLDER := $(mkfile_path)/sw/linker
COMPILER ?= gcc
COMPILER_PREFIX ?= riscv32-corev-
COMPILER_FLAGS ?= -mabi=lp64d
ARCH ?= rv64gc_zifencei
SOURCE ?=

# ============================================================================
# System Configuration
# ============================================================================
PADS_CFG ?= configs/pad_cfg.py
X_ALP_CFG  ?= configs/system.py

# Register generation tools
REGTOOL            := hw/vendor/x-heep/pulp_platform/register_interface/vendor/lowrisc_opentitan/util/regtool.py
PERIPH_STRUCTS_GEN := util/periph_structs_gen/periph_structs_gen.py
PERIPH_STRUCTS_TPL := util/periph_structs_gen/periph_structs.tpl

# Peripherals to generate registers for.
# Add peripheral name to the matching list to include it in reg-gen.
#   REG_GEN_PERIPHERALS           — generates RTL + SW header + SW structs + docs
#   REG_GEN_PERIPHERALS_BASIC     — generates RTL + SW header + docs (no structs)
#   REG_GEN_PERIPHERALS_MCU_BASIC — same as BASIC but .hjson is generated by mcu-gen;
#                                   targets also depend on $(MCU_GEN_PRIMARY) for ordering
REG_GEN_PERIPHERALS           ?= fast_intr_ctrl soc_ctrl
REG_GEN_PERIPHERALS_BASIC     ?=
REG_GEN_PERIPHERALS_MCU_BASIC ?= pad_control

# MCU-Gen template files to generate
MCU_GEN_TEMPLATES = $(shell find -L . \
  \( -path './hw/vendor/x-heep' -o -path './util/profile' \) -prune -o \
  \( -path './hw/vendor/*' -o -path './util/*' -o -path './test/*' \) -prune -o \
  -name '*.tpl' -print)

# Optionally, additional external template files can be provided to mcu-gen
EXTERNAL_MCU_GEN_TEMPLATES ?=

# Sources that trigger MCU regeneration
MCU_GEN_SOURCES  = $(MCU_GEN_TEMPLATES) $(shell find configs -type f -not -path '*/__pycache__/*')
# Output files produced by mcu_gen.py (one per .tpl, ./- prefix stripped for exact Make matching)
MCU_GEN_OUTPUTS  = $(patsubst ./%,%,$(MCU_GEN_TEMPLATES:.tpl=))
# Primary output used as the Make target (others are side effects of the same recipe)
MCU_GEN_PRIMARY := hw/x_alp.sv

# ============================================================================
# Third-party IP Vendoring
# ============================================================================
# Vendored IPs
VENDOR_FILES	:= $(shell find hw/vendor util -maxdepth 1 -type f -name "*.vendor.hjson" -print)
VENDOR_LOCKS	:= $(subst .vendor.hjson,.lock.hjson,$(VENDOR_FILES))

# Export variables to sub-makefiles
export

# ============================================================================
# Default Target
# ============================================================================
.PHONY: help
help:
	@$(mkfile_path)/util/MakefileHelp

# ============================================================================
# Environment Setup
# ============================================================================

## @section Conda
.PHONY: conda
conda:
	@conda env create -f util/conda_environment.yml

# ============================================================================
# MCU Code Generation
# ============================================================================

## @section MCU Code Generation

$(MCU_GEN_PRIMARY): $(MCU_GEN_SOURCES)
	$(PYTHON) util/xheep_gen/mcu_gen.py --config configs/python_unsupported.hjson --python_config $(X_ALP_CFG) --pads_cfg $(PADS_CFG) --outtpl "$(MCU_GEN_TEMPLATES)" --externaltpl "$(EXTERNAL_MCU_GEN_TEMPLATES)"

## Force MCU regeneration regardless of source timestamps
.PHONY: mcu-gen
mcu-gen:
	@rm -f $(MCU_GEN_PRIMARY)
	@$(MAKE) $(MCU_GEN_PRIMARY)
	@$(MAKE) reg-gen boot-rom
	@$(MAKE) format

## @section Register Generation

# Macro: RTL + SW header + SW structs + docs
# $(1) = peripheral name, $(2) = extra prerequisites (optional)
define PERIPH_GEN_FULL

hw/ip/$(1)/rtl/$(1)_reg_top.sv: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p hw/ip/$(1)/rtl
	@printf -- "Generating $(1) RTL..."; \
	 $(PYTHON) $(REGTOOL) -r -t hw/ip/$(1)/rtl $$< && printf " OK\n"

sw/device/lib/drivers/$(1)/$(1)_regs.h: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p sw/device/lib/drivers/$(1)
	@printf -- "Generating $(1) SW header..."; \
	 $(PYTHON) $(REGTOOL) --cdefines -o $$@ $$< && printf " OK\n"

sw/device/lib/drivers/$(1)/$(1)_structs.h: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p sw/device/lib/drivers/$(1)
	@printf -- "Generating $(1) SW structs..."; \
	 $(PYTHON) $(PERIPH_STRUCTS_GEN) --template_filename $(PERIPH_STRUCTS_TPL) \
	   --hjson_filename $$< --output_filename $$@ && printf " OK\n"

sw/device/lib/drivers/$(1)/$(1)_regs.md: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p sw/device/lib/drivers/$(1)
	@printf -- "Generating $(1) docs..."; \
	 $(PYTHON) $(REGTOOL) -d $$< > $$@ && printf " OK\n"

REG_GEN_OUTPUTS += \
	hw/ip/$(1)/rtl/$(1)_reg_top.sv \
	sw/device/lib/drivers/$(1)/$(1)_regs.h \
	sw/device/lib/drivers/$(1)/$(1)_structs.h \
	sw/device/lib/drivers/$(1)/$(1)_regs.md
endef

# Macro: RTL + SW header + docs (no structs)
# $(1) = peripheral name, $(2) = extra prerequisites (optional)
define PERIPH_GEN_BASIC

hw/ip/$(1)/rtl/$(1)_reg_top.sv: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p hw/ip/$(1)/rtl
	@printf -- "Generating $(1) RTL..."; \
	 $(PYTHON) $(REGTOOL) -r -t hw/ip/$(1)/rtl $$< && printf " OK\n"

sw/device/lib/drivers/$(1)/$(1)_regs.h: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p sw/device/lib/drivers/$(1)
	@printf -- "Generating $(1) SW header..."; \
	 $(PYTHON) $(REGTOOL) --cdefines -o $$@ $$< && printf " OK\n"

sw/device/lib/drivers/$(1)/$(1)_regs.md: hw/ip/$(1)/data/$(1).hjson $(2)
	@mkdir -p sw/device/lib/drivers/$(1)
	@printf -- "Generating $(1) docs..."; \
	 $(PYTHON) $(REGTOOL) -d $$< > $$@ && printf " OK\n"

REG_GEN_OUTPUTS += \
	hw/ip/$(1)/rtl/$(1)_reg_top.sv \
	sw/device/lib/drivers/$(1)/$(1)_regs.h \
	sw/device/lib/drivers/$(1)/$(1)_regs.md
endef

REG_GEN_OUTPUTS :=
$(foreach p,$(REG_GEN_PERIPHERALS),$(eval $(call PERIPH_GEN_FULL,$(p))))
$(foreach p,$(REG_GEN_PERIPHERALS_BASIC),$(eval $(call PERIPH_GEN_BASIC,$(p))))
$(foreach p,$(REG_GEN_PERIPHERALS_MCU_BASIC),$(eval $(call PERIPH_GEN_BASIC,$(p),$(MCU_GEN_PRIMARY))))

## Regenerate registers for all peripherals (incremental: only stale hjson)
.PHONY: reg-gen
reg-gen: $(REG_GEN_OUTPUTS)

## @section Boot ROM Build

# File target: incremental rebuild when bootrom sources change.
# Note: does NOT track sw/device/lib/drivers/**/*_regs.h changes; run `make boot-rom` if headers changed.
BOOTROM_SOURCES := hw/ip/bootrom/bootrom.S hw/ip/bootrom/bootrom.ld hw/ip/bootrom/gen_bootrom.py

hw/ip/bootrom/bootrom.sv: $(BOOTROM_SOURCES)
	@$(MAKE) -C hw/ip/bootrom

## Force full bootrom rebuild (use after changing driver register headers)
.PHONY: boot-rom
boot-rom:
	@$(MAKE) -C hw/ip/bootrom clean all

# ============================================================================
# Application Firmware Build
# ============================================================================

## @section APP FW Build

## Generates the build folder in sw using CMake to build (compile and linking)
## @param PROJECT=<folder_name_of_the_project_to_be_built>
## @param TARGET=sim(default),systemc,pynq-z2,nexys-a7-100t,zcu104,zcu102
## @param LINKER=on_chip(default),flash_load,flash_exec
## @param COMPILER=gcc(default),clang
## @param COMPILER_PREFIX=riscv32-corev-(default),riscv32-unknown-
## @param ARCH=rv32imc(default),<any_RISC-V_ISA_string_supported_by_the_CPU>
.PHONY: app
app: clean-app
	@$(MAKE) -C sw \
		PROJECT=$(PROJECT) \
		TARGET=$(TARGET) \
		LINKER=$(LINKER) \
		LINK_FOLDER=$(LINK_FOLDER) \
		COMPILER=$(COMPILER) \
		COMPILER_PREFIX=$(COMPILER_PREFIX) \
		COMPILER_FLAGS=$(COMPILER_FLAGS) \
		ARCH=$(ARCH) \
		SOURCE=$(SOURCE) \
	|| { \
	echo "\033[0;31mHmmm... seems like the compilation failed...\033[0m"; \
	echo "\033[0;31mIf you do not understand why, it is likely that you either:\033[0m"; \
	echo "\033[0;31m  a) offended the Leprechaun of Electronics\033[0m"; \
	echo "\033[0;31m  b) forgot to run make mcu-gen\033[0m"; \
	echo "\033[0;31m  c) forgot to set the correct compiler parameters (check the docs!)\033[0m"; \
	echo "\033[0;31mI would start by checking b) or c) if I were you!\033[0m"; \
	exit 1; \
	}
	@$(PYTHON) util/mem_usage.py

## Just list the different application names available
.PHONY: app-list
app-list:
	@echo "Note: Applications outside the X-ALP sw/applications directory will not be listed."
	@tree sw/applications/

# ============================================================================
# Simulation
# ============================================================================

## @section Simulation

## Verilator simulation build
.PHONY: verilator-build
verilator-build: $(MCU_GEN_PRIMARY) $(REG_GEN_OUTPUTS) hw/ip/bootrom/bootrom.sv
	@$(FUSESOC) --cores-root . run --no-export --target sim --tool verilator --build $(XALP) $(FUSESOC_ARGS) 2>&1 | tee buildsim.log

## Verilator simulation run
.PHONY: verilator-run
verilator-run:
	@$(FUSESOC) run --no-export --target sim --tool verilator --run $(XALP) \
		--LOG_LEVEL=$(LOG_LEVEL) \
		--BINARY=$(BINARY) \
		--BOOTMODE=$(BOOTMODE) \
		$(MAX_CYCLES_ARG) \
		--trace=true \
		$(FUSESOC_ARGS)
	@echo "Simulation finished."
	@cat ./build/x-heep_x-alp_x-alp_0.0.1/sim-verilator/uart0.log

## Verilator simulation run without waveform generation (faster)
.PHONY: verilator-opt
verilator-opt:
	@$(FUSESOC) run --no-export --target sim --tool verilator --run $(XALP) \
		--LOG_LEVEL=$(LOG_LEVEL) \
		--BINARY=$(BINARY) \
		--BOOTMODE=$(BOOTMODE) \
		$(MAX_CYCLES_ARG) \
		--trace=false \
		$(FUSESOC_ARGS)
	@echo "Simulation finished."
	@cat ./build/x-heep_x-alp_x-alp_0.0.1/sim-verilator/uart0.log

## Verilator wave viewer
.PHONY: verilator-waves
verilator-waves: .check-gtkwave
	@gtkwave build/x-heep_x-alp_x-alp_0.0.1/sim-verilator/waveform.fst util/wave.gtkw

# ============================================================================
# Code Quality
# ============================================================================

## @section formatting and linting

## Format
PHONY: format
format:
	git ls-files -z -- '*.sv' '*.svh' ':(exclude)**/vendor/**' | xargs -0 verible-verilog-format \
		--assignment_statement_alignment=align \
		--case_items_alignment=align \
		--formal_parameters_indentation=indent \
		--named_parameter_alignment=align \
		--named_parameter_indentation=indent \
		--named_port_alignment=align \
		--named_port_indentation=indent \
		--port_declarations_alignment=align \
		--port_declarations_indentation=indent \
		--module_net_variable_alignment=align \
		--indentation_spaces=4 \
		--inplace
	git ls-files -z -- '*.c' '*.h' '*.cpp' '*.hpp' ':(exclude)build/**' ':(exclude)**/vendor/**' | xargs -0 clang-format -i -style=file:util/.clang-format

## Lint
PHONY: lint
lint: .check-fusesoc
	@$(FUSESOC) $(FUSESOC_FLAGS) run --no-export --target lint $(XALP)

# ============================================================================
# Cleaning
# ============================================================================

## @section Cleaning commands

## Remove the sw build folder
.PHONY: clean-app
clean-app:
	@rm -rf sw/build

## Remove the build folders
.PHONY: clean
clean: clean-app
	@rm -rf $(BUILD_DIR) $(BUILD_STAMP)
	@rm -f $(MCU_GEN_OUTPUTS) $(REG_GEN_OUTPUTS)
	@$(MAKE) -C hw/ip/bootrom clean

## Leave the repository in a clean state, removing all generated files
.PHONY: clean-all
clean-all: clean

# ============================================================================
# Utilities & Checks
# ============================================================================

## @section Utilities

# Update the vendored IPs based on the .vendor.hjson description files
.PHONY: vendor-update
vendor-update: $(VENDOR_LOCKS)
	python3 util/check-vendor.py

$(VENDOR_LOCKS): %.lock.hjson: %.vendor.hjson util/vendor.py
	@echo "### Updating vendored IP '$(notdir $*)'..."
	python3 util/vendor.py -vU $<

.PHONY: vendor-clean
vendor-clean:
	$(RM) $(VENDOR_LOCKS)

# Check if FuseSoC is available
.check-fusesoc:
	@command -v fusesoc >/dev/null 2>&1 || { \
		printf "\033[0;31m✗ ERROR: 'fusesoc' not found in PATH\033[0m\n" >&2; \
		printf "Is the correct conda environment active?\n" >&2; \
		exit 1; \
	}

# Generic program checker template
define CHECK_PROGRAM
.PHONY: .check-$(1)
.check-$(1):
	@command -v $(2) >/dev/null 2>&1 || { \
		printf "\033[0;31m✗ ERROR: '$(2)' not found in PATH\033[0m\n" >&2; \
		exit 1; \
	}
endef

# Instantiate checks for required tools
$(eval $(call CHECK_PROGRAM,gtkwave,gtkwave))
$(eval $(call CHECK_PROGRAM,verible,verible-verilog-format))
$(eval $(call CHECK_PROGRAM,verilator,verilator))
