// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module pad_control_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 1
) (
    input  logic     clk_i,
    input  logic     rst_ni,
    input  reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

    import pad_control_reg_pkg::*;



    logic     [ -1:0] reg_steer;

    reg_req_t [0-1:0] reg_intf_demux_req;
    reg_rsp_t [0-1:0] reg_intf_demux_rsp;

    // demux connection
    assign reg_intf_req          = reg_intf_demux_req[0];
    assign reg_intf_demux_rsp[0] = reg_intf_rsp;


    // Create Socket_1n
    reg_demux #(
        .NoPorts(0),
        .req_t  (reg_req_t),
        .rsp_t  (reg_rsp_t)
    ) i_reg_demux (
        .clk_i,
        .rst_ni,
        .in_req_i   (reg_req_i),
        .in_rsp_o   (reg_rsp_o),
        .out_req_o  (reg_intf_demux_req),
        .out_rsp_i  (reg_intf_demux_rsp),
        .in_select_i(reg_steer)
    );


    // Create steering logic
    always_comb begin
        reg_steer = -1;  // Default set to register

        // TODO: Can below codes be unique case () inside ?
    end

    // Unused signal tieoff
    // devmode_i is not used if there are no registers
    logic unused_devmode;
    assign unused_devmode = ^devmode_i;
endmodule

module pad_control_reg_top_intf #(
    parameter  int AW = 1,
    localparam int DW = 32
) (
    input logic      clk_i,
    input logic      rst_ni,
          REG_BUS.in regbus_slave,
    // To HW
    // Config
    input            devmode_i      // If 1, explicit error return for unmapped register access
);
    localparam int unsigned STRB_WIDTH = DW / 8;

    `include "register_interface/typedef.svh"
    `include "register_interface/assign.svh"

    // Define structs for reg_bus
    typedef logic [AW-1:0] addr_t;
    typedef logic [DW-1:0] data_t;
    typedef logic [STRB_WIDTH-1:0] strb_t;
    `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

    reg_bus_req_t s_reg_req;
    reg_bus_rsp_t s_reg_rsp;

    // Assign SV interface to structs
    `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
    `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



    pad_control_reg_top #(
        .reg_req_t(reg_bus_req_t),
        .reg_rsp_t(reg_bus_rsp_t),
        .AW       (AW)
    ) i_regs (
        .clk_i,
        .rst_ni,
        .reg_req_i(s_reg_req),
        .reg_rsp_o(s_reg_rsp),
        .devmode_i
    );

endmodule


