// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pad_control_reg_pkg;

    // Address widths within the block
    parameter int BlockAw = 1;

endpackage

