// Copyright 2026 X-HEEP Contributors
// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// Pad ring for the X-ALP SoC design.
//
// AUTO-GENERATED by mcu_gen.py — do not edit by hand.
//





module pad_ring (

    output logic clk_o,
    inout  wire  clk_io,

    output logic rst_no,
    inout  wire  rst_nio,

    output logic jtag_tck_o,
    inout  wire  jtag_tck_io,

    output logic jtag_tms_o,
    inout  wire  jtag_tms_io,

    output logic jtag_trst_no,
    inout  wire  jtag_trst_nio,

    output logic jtag_tdi_o,
    inout  wire  jtag_tdi_io,

    input logic jtag_tdo_i,
    inout wire  jtag_tdo_io,

    output logic uart_rx_o,
    inout  wire  uart_rx_io,

    input logic uart_tx_i,
    inout wire  uart_tx_io,

    input logic exit_valid_i,
    inout wire  exit_valid_io,

    // here just for simplicity
    /* verilator lint_off UNUSED */
    input logic [core_v_mcu_pkg::NUM_PAD-1:0][0:0] pad_attributes_i
);


    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_clk (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (clk_o),
        .pad_io          (clk_io),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_rst (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (rst_no),
        .pad_io          (rst_nio),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_jtag_tck (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (jtag_tck_o),
        .pad_io          (jtag_tck_io),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_jtag_tms (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (jtag_tms_o),
        .pad_io          (jtag_tms_io),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_jtag_trst (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (jtag_trst_no),
        .pad_io          (jtag_trst_nio),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_jtag_tdi (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (jtag_tdi_o),
        .pad_io          (jtag_tdi_io),
        .pad_attributes_i('0)
    );

    pad_cell_output #(
        .PADATTR(0)
    ) u_pad_jtag_tdo (
        .pad_in_i        (jtag_tdo_i),
        .pad_oe_i        (1'b1),
        .pad_out_o       (),
        .pad_io          (jtag_tdo_io),
        .pad_attributes_i('0)
    );

    pad_cell_input #(
        .PADATTR(0)
    ) u_pad_uart_rx (
        .pad_in_i        (1'b0),
        .pad_oe_i        (1'b0),
        .pad_out_o       (uart_rx_o),
        .pad_io          (uart_rx_io),
        .pad_attributes_i('0)
    );

    pad_cell_output #(
        .PADATTR(0)
    ) u_pad_uart_tx (
        .pad_in_i        (uart_tx_i),
        .pad_oe_i        (1'b1),
        .pad_out_o       (),
        .pad_io          (uart_tx_io),
        .pad_attributes_i('0)
    );

    pad_cell_output #(
        .PADATTR(0)
    ) u_pad_exit_valid (
        .pad_in_i        (exit_valid_i),
        .pad_oe_i        (1'b1),
        .pad_out_o       (),
        .pad_io          (exit_valid_io),
        .pad_attributes_i('0)
    );


endmodule  //pad_ring
