// Copyright 2026 X-HEEP Contributors
// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// Top-level module for the X-ALP SoC design.
// Author: Luigi Giuffrida <luigi.giuffrida@polito.it>
//
// AUTO-GENERATED by mcu_gen.py — do not edit by hand.
//
<%! from XheepGen.pads.pin import Input, Output, Inout, PinDigital %>
<%
    attribute_bits = xalp.get_padring().attributes.get("bits")
    any_muxed_pads = xalp.get_padring().num_muxed_pads() > 0
%>
module x_alp (

    // ---- Pad-ring IO (auto-generated from pad configuration) ----
% for pad in xalp.get_padring().pad_list:
    <%
    has_input_pin = any(isinstance(pin, Input) for pin in pad.pins)
    has_output_pin = any(isinstance(pin, Output) for pin in pad.pins)
    has_inout_pin = any(isinstance(pin, Inout) for pin in pad.pins)
    if not (has_input_pin or has_output_pin or has_inout_pin): continue
    pin0_name = pad.pins[0].rtl_name()
    %>\
  % if has_inout_pin or (has_input_pin and has_output_pin):
    inout wire ${pin0_name}io,
  % elif has_input_pin:
    inout wire ${pin0_name}i,
  % elif has_output_pin:
    inout wire ${pin0_name}o,
  % endif
% endfor

    // ---- External Peripheral Interface ----
    output core_v_mcu_pkg::axi_slv_req_t ext_slv_req_o,
    input  core_v_mcu_pkg::axi_slv_rsp_t ext_slv_rsp_i,

    input  core_v_mcu_pkg::axi_mst_req_t ext_mst_req_i,
    output core_v_mcu_pkg::axi_mst_rsp_t ext_mst_rsp_o,

    output core_v_mcu_pkg::reg_req_t ext_reg_req_o,
    input  core_v_mcu_pkg::reg_rsp_t ext_reg_rsp_i,

    // ---- Test mode ----
    input logic test_mode_i,

    // ---- Exit interface ----
    output logic [31:0] exit_value_o

);

    // Internal signals for pad ring connections
% for pad in xalp.get_padring().pad_list:
  % for pin in pad.pins:
    % if isinstance(pin, PinDigital):
    logic ${pin.rtl_name()}in_x, ${pin.rtl_name()}out_x, ${pin.rtl_name()}oe_x;
    % endif
  % endfor
  % if len(pad.pins) > 1 and any(isinstance(pin, PinDigital) for pin in pad.pins):
    logic ${pad.pins[0].rtl_name()}in_x_muxed, ${pad.pins[0].rtl_name()}out_x_muxed, ${pad.pins[0].rtl_name()}oe_x_muxed;
  % endif
% endfor

% if attribute_bits is not None:
    logic [core_v_mcu_pkg::NUM_PAD-1:0][${attribute_bits}] pad_attributes;
% endif
% if any_muxed_pads:
    logic [core_v_mcu_pkg::NUM_PAD-1:0][${xalp.get_padring().get_muxed_pad_select_width()-1}:0] pad_muxes;
% endif

    logic rst_ngen;

    // --------------------------------------------------------
    // core_v_mcu instantiation
    // --------------------------------------------------------
    core_v_mcu u_core_v_mcu (
        .clk_i        (clk_in_x),
        .rst_ni       (rst_ngen),
        .boot_select_i(1'b0),
        .exit_valid_o (exit_valid_out_x),
        .exit_value_o (exit_value_o),
% for pin in xalp.get_padring().get_connected_pins():
  % if pin.name in ("clk", "rst", "exit_valid"):
<% continue %>
  % endif
  % if isinstance(pin, (Input, Inout)):
        .${pin.rtl_name()}i(${pin.rtl_name()}in_x),
  % endif
  % if isinstance(pin, (Output, Inout)):
        .${pin.rtl_name()}o(${pin.rtl_name()}out_x),
  % endif
  % if isinstance(pin, Inout):
        .${pin.rtl_name()}oe_o(${pin.rtl_name()}oe_x),
  % endif
% endfor
        .test_mode_i  (test_mode_i),
        .ext_slv_req_o(ext_slv_req_o),
        .ext_slv_rsp_i(ext_slv_rsp_i),
        .ext_mst_req_i(ext_mst_req_i),
        .ext_mst_rsp_o(ext_mst_rsp_o),
        .ext_reg_req_o(ext_reg_req_o),
        .ext_reg_rsp_i(ext_reg_rsp_i)
    );

    // --------------------------------------------------------
    // Pad ring instantiation
    // --------------------------------------------------------
    pad_ring pad_ring_i (
% for pad in xalp.get_padring().pad_list:
    <%
    has_input_pin = any(isinstance(pin, Input) for pin in pad.pins)
    has_output_pin = any(isinstance(pin, Output) for pin in pad.pins)
    has_inout_pin = any(isinstance(pin, Inout) for pin in pad.pins)
    if not (has_input_pin or has_output_pin or has_inout_pin): continue
    pin0_name = pad.pins[0].rtl_name()
    muxed_string = "_muxed" if pad.is_muxed() else ""
    %>\
  % if has_inout_pin or (has_input_pin and has_output_pin):
        .${pin0_name}i(${pin0_name}out_x${muxed_string}),
        .${pin0_name}oe_i(${pin0_name}oe_x${muxed_string}),
        .${pin0_name}o(${pin0_name}in_x${muxed_string}),
        .${pin0_name}io(${pin0_name}io),
  % elif has_input_pin:
        .${pin0_name}o(${pin0_name}in_x${muxed_string}),
        .${pin0_name}io(${pin0_name}i),
  % elif has_output_pin:
        .${pin0_name}i(${pin0_name}out_x${muxed_string}),
        .${pin0_name}io(${pin0_name}o${muxed_string}),
  % endif
% endfor
  % if attribute_bits is not None:
        .pad_attributes_i(pad_attributes)
  % else:
        .pad_attributes_i('0)
  % endif
    );

    // --------------------------------------------------------
    // Default signal assignments
    // --------------------------------------------------------
% for pin in xalp.get_padring().pin_list:
  % if isinstance(pin, Input):
    assign ${pin.rtl_name()}out_x = 1'b0;
    assign ${pin.rtl_name()}oe_x = 1'b0;
  % endif
  % if isinstance(pin, Output):
    assign ${pin.rtl_name()}oe_x = 1'b1;
  % endif
% endfor

    // --------------------------------------------------------
    // Pad multiplexers
    // --------------------------------------------------------
% for pad in [pad for pad in xalp.get_padring().pad_list if pad.is_muxed() and any(isinstance(pin, PinDigital) for pin in pad.pins)]:
    <% pin0_name = pad.pins[0].rtl_name() %>\
    always_comb begin
      % for pin in pad.pins:
        ${pin.rtl_name()}in_x = 1'b0;
      % endfor
        unique case(pad_muxes[core_v_mcu_pkg::PAD_${pad.name.upper()}])
      % for idx, pin in enumerate(pad.pins):
            ${idx}: begin
                <% pinidx_name = pin.rtl_name() %>\
                ${pin0_name}out_x_muxed = ${pinidx_name}out_x;
                ${pin0_name}oe_x_muxed  = ${pinidx_name}oe_x;
                ${pinidx_name}in_x        = ${pin0_name}in_x_muxed;
            end
      % endfor
            default: begin
                ${pin0_name}out_x_muxed = ${pin0_name}out_x;
                ${pin0_name}oe_x_muxed  = ${pin0_name}oe_x;
                ${pin0_name}in_x        = ${pin0_name}in_x_muxed;
            end
        endcase
    end
% endfor

    // --------------------------------------------------------
    // Reset generator
    // --------------------------------------------------------
    rstgen rstgen_i (
        .clk_i    (clk_in_x),
        .rst_ni   (rst_nin_x),
        .test_mode_i(1'b0),
        .rst_no   (rst_ngen),
        .init_no  ()
    );

endmodule : x_alp
